/**:
  ros__parameters:
    robot_description_kinematics:
      arm_0:
        kinematics_solver: pick_ik/PickIKKinematicsPlugin
        kinematics_solver_timeout: 0.005
        kinematics_solver_attempts: 3
        mode: global