/j100_0921/move_group:
  ros__parameters:
    sensors:
      - camera_1

    camera_1:
      sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
      point_cloud_topic: /j100_0921/sensors/camera_1/points_filtered # /j100_0921/sensors/camera_1/points_filtered  #/j100_0921/sensors/camera_1/points
      max_range: 0.8
      point_subsample: 1
      padding_offset: 0.01
      padding_scale: 1.2
      max_update_rate: 2.0
      filtered_cloud_topic: /j100_0921/sensors/camera_1/filtered_cloud

    octomap_frame: odom #arm_0_base_link
    octomap_resolution: 0.01
    max_range: 0.8