#!/usr/bin/env python3

import os
import xacro
import yaml
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction, ExecuteProcess, RegisterEventHandler
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory
from clearpath_config.clearpath_config import ClearpathConfig
from clearpath_config.common.utils.yaml import read_yaml
from launch.event_handlers import OnProcessStart


def launch_setup(context, *args, **kwargs):
    # Launch Configurations
    setup_path = LaunchConfiguration('setup_path')
    use_sim_time = LaunchConfiguration('use_sim_time')
    setup_path_context = setup_path.perform(context)

    # Read and parse robot YAML
    config = read_yaml(os.path.join(setup_path_context, 'robot.yaml'))
    clearpath_config = ClearpathConfig(config)

    # Dynamic Namespace
    namespace = clearpath_config.system.namespace

    # Robot Description (URDF)
    robot_description = {
        'robot_description': xacro.process_file(
            os.path.join(setup_path_context, 'robot.urdf.xacro')
        ).toxml()
    }

    # Semantic Robot Description (SRDF)
    robot_description_semantic = {
        'robot_description_semantic': xacro.process_file(
            os.path.join(setup_path_context, 'robot.srdf')
        ).toxml()
    }

    # Load Servo Configuration
    servo_yaml = os.path.join(
        get_package_share_directory('mtu32_bringup'),
        "config", "j100", "servo_config.yaml"
    )

    # MoveIt config (generated by Clearpath). move_group loads this file directly;
    # Servo doesn't, so pull out the sections it needs.
    moveit_yaml_path = os.path.join(setup_path_context, 'manipulators', 'config', 'moveit.yaml')
    with open(moveit_yaml_path, "r") as f:
        full_moveit_config = yaml.safe_load(f) or {}

    move_group_params = (
        full_moveit_config.get(namespace, {}).get('move_group', {}).get('ros__parameters')
    )
    if move_group_params is None:
        print(f"[moveit.launch.py] WARNING: '{namespace}/move_group/ros__parameters' "
              f"not found in {moveit_yaml_path}; Servo will use default kinematics/limits.")
        move_group_params = {}

    # Kinematics (gripper group has no IK)
    kinematics_dict = dict(move_group_params.get('robot_description_kinematics', {}))
    kinematics_dict.pop("arm_0_gripper", None)
    kinematics_dict["arm_0"] = {
        **kinematics_dict.get("arm_0", {}),
        "kinematics_solver": "kdl_kinematics_plugin/KDLKinematicsPlugin",
        "kinematics_solver_timeout": 0.05,             # seconds per IK call
        "kinematics_solver_search_resolution": 0.005,  # radians
        "kinematics_solver_attempts": 3,
    }
    robot_description_kinematics = {"robot_description_kinematics": kinematics_dict}

    # Joint velocity/acceleration limits (the same values that are in moveit.yaml)
    robot_description_planning = {
        "robot_description_planning": move_group_params.get('robot_description_planning', {})
    }


    # MoveIt Move Group Node
    move_group_node = Node(
        package='moveit_ros_move_group',
        executable='move_group',
        output='screen',
        namespace=namespace,
        parameters=[
            moveit_yaml_path,
            robot_description,
            robot_description_semantic,
            robot_description_kinematics,  # overrides the IK timeout in moveit.yaml
            robot_description_planning,
            {'use_sim_time': use_sim_time},
        ],
        remappings=[
            ('/tf', 'tf'),
            ('/tf_static', 'tf_static'),
            ('joint_states', 'platform/joint_states'),
        ]
    )

    # MoveIt Servo Node
    servo_node = Node(
        package="moveit_servo",
        executable="servo_node",
        name="servo_node",
        namespace=namespace,
        parameters=[
            servo_yaml,
            robot_description,
            robot_description_semantic,
            robot_description_kinematics,
            robot_description_planning,
            {"use_sim_time": use_sim_time},
        ],
        remappings=[
            ('/tf', 'tf'),
            ('/tf_static', 'tf_static'),
            ('joint_states', 'platform/joint_states'),
        ],
        output="screen",
    )

    # Optional: Command Mode Activation Event Handler
    activate_twist_mode = ExecuteProcess(
        cmd=[
            "ros2", "service", "call",
            f"/{namespace}/servo_node/switch_command_type",
            "moveit_msgs/srv/ServoCommandType",
            "{command_type: 1}"
        ],
        output="screen"
    )

    servo_start_handler = RegisterEventHandler(
        event_handler=OnProcessStart(
            target_action=servo_node,
            on_start=[activate_twist_mode],
        )
    )

    return [
        move_group_node,
        servo_node,
        servo_start_handler
    ]


def generate_launch_description():
    arg_setup_path = DeclareLaunchArgument(
        'setup_path',
        default_value='/etc/clearpath/',
        description='Clearpath setup path'
    )
    arg_use_sim_time = DeclareLaunchArgument(
        'use_sim_time',
        default_value='false',
        choices=['true', 'false'],
        description='use_sim_time'
    )

    ld = LaunchDescription()
    ld.add_action(arg_setup_path)
    ld.add_action(arg_use_sim_time)
    ld.add_action(OpaqueFunction(function=launch_setup))
    return ld